# Ensure script is running as Administrator
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Host "Please run this script as Administrator!" -ForegroundColor Red
    exit
}

# Get the root directory of the devkit
$devkitRoot = $PSScriptRoot | Split-Path | Split-Path
$powershellConfig = Join-Path $devkitRoot "configuration\powershell"
$ompTheme = Join-Path $devkitRoot "configuration\.mytheme-new.omp.json"

# Create variables.ps1 with the correct paths
$variablesContent = @"
# DevKit Environment Variables
# This file is automatically generated by the install script
# Do not modify manually

# Root directory of the devkit installation
`$env:DEVKIT_ROOT = "$devkitRoot"

# Path to the PowerShell configuration directory
`$env:DEVKIT_POWERSHELL_CONFIG = "$powershellConfig"

# Path to the oh-my-posh theme
`$env:DEVKIT_OMP_THEME = "$ompTheme"
"@

$variablesPath = Join-Path $powershellConfig "variables.ps1"
$variablesContent | Out-File -FilePath $variablesPath -Encoding UTF8

# Set execution policy to allow module installation
Write-Host "Setting execution policy..." -ForegroundColor Cyan
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

# List of required modules
$requiredModules = @(
    "z",
    "posh-git",
    "Terminal-Icons",
    "PSReadLine"
)

# Function to check and install missing modules
function Install-ModuleIfMissing {
    param (
        [string]$moduleName
    )

    if (-not (Get-Module -ListAvailable -Name $moduleName)) {
        Write-Host "Installing module: $moduleName" -ForegroundColor Yellow
        Install-Module -Name $moduleName -Scope CurrentUser -Force -AllowClobber
    } else {
        Write-Host "Module $moduleName is already installed." -ForegroundColor Green
    }
}

# Ensure PowerShell Gallery is trusted
$gallerySource = Get-PSRepository | Where-Object { $_.Name -eq "PSGallery" }
if ($gallerySource -and $gallerySource.InstallationPolicy -ne "Trusted") {
    Write-Host "Trusting PowerShell Gallery..." -ForegroundColor Cyan
    Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
}

# Install required modules
foreach ($module in $requiredModules) {
    Install-ModuleIfMissing -moduleName $module
}

Write-Host "All necessary modules are installed!" -ForegroundColor Magenta

Write-Host "Installing oh-my-posh" -ForegroundColor Yellow

Set-ExecutionPolicy Bypass -Scope Process -Force;
Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))

Write-Host "Oh-my-posh installed!" -ForegroundColor Magenta

# Update user's PowerShell profile
$userProfile = $PROFILE
$profileContent = @"
# DevKit Profile Configuration
# This section was automatically added by the DevKit install script
# Do not modify manually

# Import DevKit variables
. "$variablesPath"

# Import DevKit ReadPath profile
. "$powershellConfig\Microsoft.PowerShell.ReadPath_profile.ps1"
"@

# Check if the profile already contains our configuration
$existingProfile = if (Test-Path $userProfile) { Get-Content $userProfile } else { "" }
if (-not ($existingProfile -match "DevKit Profile Configuration")) {
    Write-Host "Updating PowerShell profile..." -ForegroundColor Cyan
    $profileContent | Out-File -FilePath $userProfile -Append -Encoding UTF8
    Write-Host "PowerShell profile updated successfully!" -ForegroundColor Green
} else {
    Write-Host "PowerShell profile already contains DevKit configuration." -ForegroundColor Yellow
}

Write-Host "`nInstallation complete! Please restart your PowerShell session for changes to take effect." -ForegroundColor Green