# Devkit Environment Variables
# Generated by Devkit Installation Wizard

$env:DEVKIT_ROOT = "C:/repos/usualexpat/usualexpat-devkit"
$env:DEVKIT_POWERSHELL_CONFIG = "$env:DEVKIT_ROOT/configuration/powershell"
$env:DEVKIT_OMP_THEME = "C:/repos/usualexpat/usualexpat-devkit/configuration/powershell/.mytheme-new.omp.json"
